// One-Time Pad: the same letter-addition math as Vigenere, but the whole point of this cipher
// isn't the math — it's key discipline. A one-time pad is only perfectly secret if its key is
// truly random, at least as long as the message, and never reused. This implementation can't
// enforce "never reused" (there's nothing stopping someone encrypting twice with the same key),
// but it can and does flag the moment the key *wraps around* during a single run — that's exactly
// when a short, reused key breaks the guarantee, made visible instead of silently "just working".
import { register } from '../core/cipherRegistry.js';

function shiftLetter(char, shift) {
    if (!/[a-zA-Z]/.test(char)) return char;
    const base = char === char.toLowerCase() ? 97 : 65;
    const code = char.charCodeAt(0) - base;
    const shifted = ((code + shift) % 26 + 26) % 26;
    return String.fromCharCode(shifted + base);
}

function normalizeKey(rawKey) {
    return (rawKey || '').toUpperCase().replace(/[^A-Z]/g, '') || 'X';
}

function generateRandomKey(length) {
    let key = '';
    for (let i = 0; i < length; i++) {
        key += String.fromCharCode(65 + Math.floor(Math.random() * 26));
    }
    return key;
}

// Generated once when the module loads — a fresh random pad each page load.
const DEFAULT_KEY = generateRandomKey(100);

function* otpSteps(text, params, mode) {
    const key = normalizeKey(params.key);
    let letterCount = 0;

    for (let i = 0; i < text.length; i++) {
        const oldChar = text[i];
        if (/[a-zA-Z]/.test(oldChar)) {
            const keyLetter = key[letterCount % key.length];
            const keyReused = letterCount >= key.length;
            const shift = keyLetter.charCodeAt(0) - 65;
            const direction = mode === 'encrypt' ? shift : -shift;
            const newChar = shiftLetter(oldChar, direction);
            const sign = mode === 'encrypt' ? '+' : '-';
            const reuseNote = keyReused
                ? ' ⚠ Key letter reused here (key ran out) — this breaks perfect secrecy!'
                : '';
            letterCount++;
            yield {
                index: i,
                oldChar,
                newChar,
                explanation: `One-Time Pad: Using key letter '${keyLetter}' (shift: ${sign}${shift}) on '${oldChar}'.${reuseNote}`,
            };
        } else {
            yield {
                index: i,
                oldChar,
                newChar: oldChar,
                explanation: `Not changing '${oldChar}' because it's not a letter`,
            };
        }
    }
}

function runFull(text, params, mode) {
    const chars = text.split('');
    for (const step of otpSteps(text, params, mode)) {
        chars[step.index] = step.newChar;
    }
    return chars.join('');
}

register({
    id: 'onetimepad',
    name: 'One-Time Pad',
    category: 'modern',
    description:
        'Adds a key to each letter, the same way Vigenere does — but a true one-time pad requires three things the math alone can’t guarantee: ' +
        'the key must be truly random, at least as long as the message, and never reused for another message. ' +
        'If all three hold, this is the only cipher proven mathematically unbreakable (perfect secrecy) — not even unlimited computing power can crack it. ' +
        'A long random key is generated by default, but if your message runs longer than the key, it wraps around and repeats — watch the step explanation for a warning when that happens, since a real one-time pad must never do that. ' +
        'Security level: perfect, if and only if the key is random, as long as the message, and used once — otherwise it’s just Vigenere with extra steps. ' +
        'Best used for: understanding what "provably unbreakable" actually requires.',
    paramsSchema: [
        { name: 'key', label: 'One-Time Key (random letters)', type: 'text', default: DEFAULT_KEY },
    ],

    encrypt(text, params) {
        return runFull(text, params, 'encrypt');
    },
    decrypt(text, params) {
        return runFull(text, params, 'decrypt');
    },
    stepThrough: otpSteps,
});
